Started GET "/" for ::1 at 2022-09-14 15:06:43 -0700
  
ActiveRecord::NoDatabaseError (connection to server on socket "/tmp/.s.PGSQL.5432" failed: FATAL:  database "social_networks_development" does not exist
):
  
activerecord (6.1.7) lib/active_record/connection_adapters/postgresql_adapter.rb:81:in `rescue in new_client'
activerecord (6.1.7) lib/active_record/connection_adapters/postgresql_adapter.rb:77:in `new_client'
activerecord (6.1.7) lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `postgresql_connection'
activerecord (6.1.7) lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `public_send'
activerecord (6.1.7) lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `new_connection'
activerecord (6.1.7) lib/active_record/connection_adapters/abstract/connection_pool.rb:926:in `checkout_new_connection'
activerecord (6.1.7) lib/active_record/connection_adapters/abstract/connection_pool.rb:905:in `try_to_checkout_new_connection'
activerecord (6.1.7) lib/active_record/connection_adapters/abstract/connection_pool.rb:866:in `acquire_connection'
activerecord (6.1.7) lib/active_record/connection_adapters/abstract/connection_pool.rb:588:in `checkout'
activerecord (6.1.7) lib/active_record/connection_adapters/abstract/connection_pool.rb:428:in `connection'
activerecord (6.1.7) lib/active_record/connection_adapters/abstract/connection_pool.rb:1128:in `retrieve_connection'
activerecord (6.1.7) lib/active_record/connection_handling.rb:327:in `retrieve_connection'
activerecord (6.1.7) lib/active_record/connection_handling.rb:283:in `connection'
activerecord (6.1.7) lib/active_record/migration.rb:611:in `connection'
activerecord (6.1.7) lib/active_record/migration.rb:606:in `build_watcher'
activerecord (6.1.7) lib/active_record/migration.rb:588:in `block in call'
activerecord (6.1.7) lib/active_record/migration.rb:587:in `synchronize'
activerecord (6.1.7) lib/active_record/migration.rb:587:in `call'
actionpack (6.1.7) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.1.7) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (6.1.7) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.1.7) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.7) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.1.7) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
actionpack (6.1.7) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.1.7) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.1.7) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.1.7) lib/active_support/tagged_logging.rb:99:in `block in tagged'
activesupport (6.1.7) lib/active_support/tagged_logging.rb:37:in `tagged'
activesupport (6.1.7) lib/active_support/tagged_logging.rb:99:in `tagged'
railties (6.1.7) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.1.7) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.1.7) lib/action_dispatch/middleware/request_id.rb:26:in `call'
rack (2.2.4) lib/rack/runtime.rb:22:in `call'
activesupport (6.1.7) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.1.7) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.7) lib/action_dispatch/middleware/static.rb:24:in `call'
rack (2.2.4) lib/rack/sendfile.rb:110:in `call'
actionpack (6.1.7) lib/action_dispatch/middleware/host_authorization.rb:148:in `call'
railties (6.1.7) lib/rails/engine.rb:539:in `call'
puma (5.6.5) lib/puma/configuration.rb:252:in `call'
puma (5.6.5) lib/puma/request.rb:77:in `block in handle_request'
puma (5.6.5) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
puma (5.6.5) lib/puma/request.rb:76:in `handle_request'
puma (5.6.5) lib/puma/server.rb:443:in `process_client'
puma (5.6.5) lib/puma/thread_pool.rb:147:in `block in spawn_thread'
  [1m[35m (450.2ms)[0m  [1m[35mCREATE DATABASE "social_networks_development" ENCODING = 'unicode'[0m
  [1m[35m (59.8ms)[0m  [1m[35mCREATE DATABASE "social_networks_test" ENCODING = 'unicode'[0m
Started GET "/" for ::1 at 2022-09-14 15:07:13 -0700
  
AbstractController::ActionNotFound (The action 'show' could not be found for SocialNetworksController):
  
actionpack (6.1.7) lib/abstract_controller/base.rb:160:in `process'
actionpack (6.1.7) lib/action_controller/metal.rb:190:in `dispatch'
actionpack (6.1.7) lib/action_controller/metal.rb:254:in `dispatch'
actionpack (6.1.7) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
actionpack (6.1.7) lib/action_dispatch/routing/route_set.rb:33:in `serve'
actionpack (6.1.7) lib/action_dispatch/journey/router.rb:50:in `block in serve'
actionpack (6.1.7) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.1.7) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.1.7) lib/action_dispatch/routing/route_set.rb:842:in `call'
rack (2.2.4) lib/rack/etag.rb:27:in `call'
rack (2.2.4) lib/rack/conditional_get.rb:27:in `call'
rack (2.2.4) lib/rack/head.rb:12:in `call'
activerecord (6.1.7) lib/active_record/migration.rb:601:in `call'
actionpack (6.1.7) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.1.7) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (6.1.7) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.1.7) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.7) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.1.7) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
actionpack (6.1.7) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.1.7) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.1.7) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.1.7) lib/active_support/tagged_logging.rb:99:in `block in tagged'
activesupport (6.1.7) lib/active_support/tagged_logging.rb:37:in `tagged'
activesupport (6.1.7) lib/active_support/tagged_logging.rb:99:in `tagged'
railties (6.1.7) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.1.7) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.1.7) lib/action_dispatch/middleware/request_id.rb:26:in `call'
rack (2.2.4) lib/rack/runtime.rb:22:in `call'
activesupport (6.1.7) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.1.7) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.7) lib/action_dispatch/middleware/static.rb:24:in `call'
rack (2.2.4) lib/rack/sendfile.rb:110:in `call'
actionpack (6.1.7) lib/action_dispatch/middleware/host_authorization.rb:148:in `call'
railties (6.1.7) lib/rails/engine.rb:539:in `call'
puma (5.6.5) lib/puma/configuration.rb:252:in `call'
puma (5.6.5) lib/puma/request.rb:77:in `block in handle_request'
puma (5.6.5) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
puma (5.6.5) lib/puma/request.rb:76:in `handle_request'
puma (5.6.5) lib/puma/server.rb:443:in `process_client'
puma (5.6.5) lib/puma/thread_pool.rb:147:in `block in spawn_thread'
Started GET "/" for ::1 at 2022-09-14 15:07:32 -0700
Processing by SocialNetworksController#index as */*
Completed 200 OK in 2716ms (Views: 0.8ms | ActiveRecord: 0.0ms | Allocations: 6847)


Started GET "/" for ::1 at 2022-09-14 15:07:43 -0700
Processing by SocialNetworksController#index as */*
Completed 500 Internal Server Error in 2689ms (ActiveRecord: 0.0ms | Allocations: 2856)


  
JSON::ParserError (767: unexpected token at 'I am trapped in a social media factory send help'):
  
lib/take_home/client.rb:20:in `instagram_data'
app/services/take_home_service.rb:14:in `data'
app/controllers/social_networks_controller.rb:3:in `index'
Started GET "/" for ::1 at 2022-09-14 15:07:51 -0700
Processing by SocialNetworksController#index as */*
Completed 500 Internal Server Error in 924ms (ActiveRecord: 0.0ms | Allocations: 961)


  
JSON::ParserError (767: unexpected token at 'I am trapped in a social media factory send help'):
  
lib/take_home/client.rb:12:in `twitter_data'
app/services/take_home_service.rb:12:in `data'
app/controllers/social_networks_controller.rb:3:in `index'
Started GET "/" for ::1 at 2022-09-14 15:08:00 -0700
Processing by SocialNetworksController#index as */*
Completed 200 OK in 2704ms (Views: 0.5ms | ActiveRecord: 0.0ms | Allocations: 3217)


Started GET "/" for ::1 at 2022-09-14 15:08:06 -0700
Processing by SocialNetworksController#index as */*
Completed 200 OK in 2705ms (Views: 1.0ms | ActiveRecord: 0.0ms | Allocations: 3220)


Started GET "/" for ::1 at 2022-09-14 15:08:11 -0700
Processing by SocialNetworksController#index as */*
Completed 200 OK in 2689ms (Views: 1.5ms | ActiveRecord: 0.0ms | Allocations: 3228)


Started GET "/" for ::1 at 2022-09-14 15:11:15 -0700
Processing by SocialNetworksController#index as */*
Completed 422 Unprocessable Entity in 2993ms (Views: 0.2ms | ActiveRecord: 0.0ms | Allocations: 2897)


Started GET "/" for ::1 at 2022-09-14 15:11:20 -0700
Processing by SocialNetworksController#index as */*
Completed 422 Unprocessable Entity in 1797ms (Views: 0.7ms | ActiveRecord: 0.0ms | Allocations: 1875)


Started GET "/" for ::1 at 2022-09-14 15:11:23 -0700
Processing by SocialNetworksController#index as */*
Completed 422 Unprocessable Entity in 884ms (Views: 1.1ms | ActiveRecord: 0.0ms | Allocations: 938)


Started GET "/" for ::1 at 2022-09-14 15:11:25 -0700
Processing by SocialNetworksController#index as */*
Completed 200 OK in 2689ms (Views: 1.2ms | ActiveRecord: 0.0ms | Allocations: 3209)


Started GET "/" for ::1 at 2022-09-14 15:11:47 -0700
Processing by SocialNetworksController#index as */*
Completed 422 Unprocessable Entity in 873ms (Views: 0.8ms | ActiveRecord: 0.0ms | Allocations: 1018)


Started GET "/" for ::1 at 2022-09-14 15:11:52 -0700
Processing by SocialNetworksController#index as */*
Completed 200 OK in 2759ms (Views: 1.1ms | ActiveRecord: 0.0ms | Allocations: 3224)


Started GET "/" for ::1 at 2022-09-14 15:13:41 -0700
Processing by SocialNetworksController#index as */*
Completed 422 Unprocessable Entity in 1792ms (Views: 0.8ms | ActiveRecord: 0.0ms | Allocations: 1885)


Started GET "/" for ::1 at 2022-09-14 15:13:45 -0700
Processing by SocialNetworksController#index as */*
Completed 422 Unprocessable Entity in 1776ms (Views: 0.5ms | ActiveRecord: 0.0ms | Allocations: 1876)


Started GET "/" for ::1 at 2022-09-14 15:13:49 -0700
Processing by SocialNetworksController#index as */*
Completed 422 Unprocessable Entity in 898ms (Views: 0.6ms | ActiveRecord: 0.0ms | Allocations: 942)


Started GET "/" for ::1 at 2022-09-14 15:13:51 -0700
Processing by SocialNetworksController#index as */*
Completed 422 Unprocessable Entity in 895ms (Views: 0.6ms | ActiveRecord: 0.0ms | Allocations: 939)


Started GET "/" for ::1 at 2022-09-14 15:13:53 -0700
Processing by SocialNetworksController#index as */*
Completed 422 Unprocessable Entity in 899ms (Views: 0.3ms | ActiveRecord: 0.0ms | Allocations: 939)


Started GET "/" for ::1 at 2022-09-14 15:13:57 -0700
Processing by SocialNetworksController#index as */*
Completed 200 OK in 2786ms (Views: 2.4ms | ActiveRecord: 0.0ms | Allocations: 3212)


Started GET "/" for ::1 at 2022-09-14 15:18:22 -0700
Processing by SocialNetworksController#index as */*
Completed 500 Internal Server Error in 4ms (ActiveRecord: 0.0ms | Allocations: 2607)


  
ArgumentError (wrong number of arguments (given 3, expected 1..2)):
  
lib/take_home/client.rb:12:in `twitter_data'
app/services/take_home_service.rb:12:in `data'
app/controllers/social_networks_controller.rb:3:in `index'
Started GET "/" for ::1 at 2022-09-14 15:18:42 -0700
Processing by SocialNetworksController#index as */*
Completed 500 Internal Server Error in 1ms (ActiveRecord: 0.0ms | Allocations: 101)


  
ArgumentError (wrong number of arguments (given 3, expected 1..2)):
  
lib/take_home/client.rb:12:in `twitter_data'
app/services/take_home_service.rb:12:in `data'
app/controllers/social_networks_controller.rb:3:in `index'
Started GET "/" for ::1 at 2022-09-14 15:18:48 -0700
Processing by SocialNetworksController#index as */*
Completed 500 Internal Server Error in 0ms (ActiveRecord: 0.0ms | Allocations: 101)


  
ArgumentError (wrong number of arguments (given 3, expected 1..2)):
  
lib/take_home/client.rb:12:in `twitter_data'
app/services/take_home_service.rb:12:in `data'
app/controllers/social_networks_controller.rb:3:in `index'
Started GET "/" for ::1 at 2022-09-14 15:18:55 -0700
Processing by SocialNetworksController#index as */*
Completed 200 OK in 2942ms (Views: 1.6ms | ActiveRecord: 0.0ms | Allocations: 5783)


Started GET "/" for ::1 at 2022-09-14 15:19:00 -0700
Processing by SocialNetworksController#index as */*
Completed 200 OK in 2752ms (Views: 0.7ms | ActiveRecord: 0.0ms | Allocations: 3216)


Started GET "/" for ::1 at 2022-09-14 15:46:11 -0700
Processing by SocialNetworksController#index as */*
Completed 200 OK in 2994ms (Views: 1.4ms | Allocations: 3299)


